version: '2'
services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "80:80"

  integration-tests:
    depends_on:
      - httpbin
    environment:
      - HTTBIN_API=http://httpbin:80
    build:
      context: ..
      dockerfile: 'build/client/Dockerfile'