name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v -race -count=1 -cover ./...
