name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit tests
        run: go test -race -short -v -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Integration tests with HTTP BIN
        run: |
          docker-compose -f ./deployments/docker-compose.yml -p up --build --exit-code-from